### ISSUE TITLE
Report throughput / TPS individually for each thread / flow

### ISSUE THREAD

**Issue by jsitnicki** [rushit-tool/rushit#1]
Currently, at the end of a run, we report throughput / TPS aggregated from all threads and all flows. This prevents users from reasoning about distribution of throughput / TPS among threads/flows.

Calculate througput/TPS for each flow individually and report it, in addition to printing the aggregated value as we do now.

Suggested by @olichtne.

**Comment by jsitnicki** [comment]
I have a WIP branch for this feature that I'm currently testing:

https://github.com/jsitnicki/rushit/commits/wip-tput-per-flow

The output would look like so:

UDP stream
----------
```
server $ ./udp_stream -T 5
[...]
throughput_Mbps=25433.16
throughput_Mbps[0]=5148.66
throughput_Mbps[1]=4326.48
throughput_Mbps[2]=4757.03
throughput_Mbps[3]=4118.87
throughput_Mbps[4]=5426.10
correlation_coefficient=1.00
time_end=115827.476457592
server $
```
```
client $ ./udp_stream -F 5 -T 5 -c
[...]
throughput_Mbps=30867.76
throughput_Mbps[0]=6189.74
throughput_Mbps[1]=5172.42
throughput_Mbps[2]=5846.87
throughput_Mbps[3]=4595.85
throughput_Mbps[4]=6287.20
correlation_coefficient=1.00
time_end=115827.476430344
client $
```
TCP stream
----------
```
server $ ./tcp_stream -T 5
[...]
throughput_Mbps=36225.78
throughput_Mbps[0]=0.00
throughput_Mbps[1]=5866.39
throughput_Mbps[2]=0.00
throughput_Mbps[3]=15005.10
throughput_Mbps[4]=13832.37
correlation_coefficient=1.00
time_end=116015.576700515
server $
```
```
client $ ./tcp_stream -F 5 -T 5 -c
[...]
client $
```
Notes:

* There is no client-side throughput reporting for TCP stream workload at the
  moment.

* Because we're using SO_REUSEPORT some TCP server threads handle more than one
  connection while others idle. SO_REUSEPORT cannot be turned off for TCP stream
  workload currently.

* Reported per thread throughput from all threads don't add up to less than the
  as the total reported throughput. Need to double-check the statistics
  calculations to figure out where the difference is coming from.

**Comment by jtluka** [comment]
Do I get it right that the units are encoded in the string? E.g.
`throughput_Mbps[0]=0.00`
says the throughput is in Mbps? What are the other units that rushit could report? Wondering if it's better to report in 'bps' only rather than parsing the modificator?

**Comment by jsitnicki** [comment]
This is the only unit that is supported ATM. That is - you will never see any other key in the output, like `throughput_Gbps` or `throughput_kbps`.

It's something we have inherited from the base project, actually. I haven't given it much thought until now. Why Mbps? My guess is that it's because that's the unit `netperf` uses as the default. 

Internally we're calculating throughput in bytes/second, the measurement is converted to Mbps only just before printing.

It makes sense to me to switch it to `bps`, like you're suggesting, so that there is no ambiguity if value was rounded off.

`bps` won't be very human friendly but the current output format isn't pretty anyway so it's just a part of bigger problem we'll have to deal with.

**Comment by olichtne** [comment]
Hi,

sorry for the later response, I was on PTO last week...

The output format looks good for now. As @jtluka mentioned, the "_\<unit\>" format could perhaps be improved but it's not critical.

Wrt. SO_REUSEPORT... that looks unfortunate, I would normally expect it to load balance uniformly, wouldn't this also potentially affect the measured throughput? If a single thread is handling two streams and another thread is idling then the performance could end up being lower in case the active thread gets cpu bottlenecked? And since the stream handling could change between multiple runs of the benchmark this could affect result stability, in that case I would opt for not using SO_REUSEPORT.

In the end I'll have to handle 0 throughput, by some threads, differently than my original assumption of 0=="fail", since I expect the same will happen in case the server has more rx threads than the client has for tx.

**Comment by jsitnicki** [comment]
Thanks for feedback @olichtne. This doesn't seem right, I was expecting `SO_REUSEPORT` to distribute connections fairly among threads. I've opened a bug for it and will dig deeper - see issue https://github.com/rushit-tool/rushit/issues/10.

An alternative would be to make use of `SO_REUSEPORT` optional, so that if disabled each TCP server listens on its own port. We provide this option already for UDP stream workload so it would be good to add it to have feature parity between UDP and TCP workloads.

**Comment by jsitnicki** [comment]
We still need support for reporting throughput in other units than Mbps and a way to fairly distribute connections among TCP threads, but basic support for per thread throughput reporting is in. Closing this one.
